# Generated by Django 5.2.3 on 2025-06-22 14:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NFT',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='NFT Name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='NFT Price')),
                ('author', models.CharField(max_length=255, verbose_name='NFT Author')),
            ],
        ),
    ]
