# Generated by Django 5.2.3 on 2025-06-22 20:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nft', '0004_alter_nft_img'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NFTEventTags',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='NFT Event Tag Name')),
            ],
        ),
        migrations.AlterField(
            model_name='nft',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='NFT Name'),
        ),
        migrations.CreateModel(
            name='NFTCollection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='NFT Collection Name')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('nfts', models.ManyToManyField(to='nft.nft')),
            ],
        ),
        migrations.CreateModel(
            name='NFTEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150, verbose_name='NFT Event Title')),
                ('description', models.TextField(max_length=5000, verbose_name='NFT Event Description')),
                ('timestamp', models.DateTimeField(verbose_name='NFT Event Timestamp')),
                ('tags', models.ManyToManyField(to='nft.nfteventtags')),
            ],
        ),
    ]
