# Generated by Django 5.2.3 on 2025-06-23 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nft', '0005_nfteventtags_alter_nft_name_nftcollection_nftevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='nftevent',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='nftevent',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='nftevent',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nftevent',
            name='timeset',
            field=models.DateTimeField(blank=True, null=True, verbose_name='NFT Event Timestamp'),
        ),
    ]
