# Generated by Django 5.2.3 on 2025-06-23 17:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nft', '0006_rename_title_nftevent_name_remove_nftevent_timestamp_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='nftevent',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='nftevent',
            name='timeset',
            field=models.DateTimeField(verbose_name='NFT Event Timestamp'),
        ),
    ]
